package com.mickeymeng.admin.system.api.errorcode;

import com.mickeymeng.framework.common.service.dto.ErrorCodeAutoGenerateReqDTO;
import com.mickeymeng.framework.common.service.dto.ErrorCodeRespDTO;
import com.mickeymeng.admin.system.service.errorcode.ErrorCodeService;
import com.mickeymeng.framework.common.service.api.ErrorCodeApi;
import org.springframework.stereotype.Service;

import javax.annotation.Resource;
import java.time.LocalDateTime;
import java.util.List;

/**
 * 错误码 Api 实现类
 *
 * @author 芋道源码
 */
@Service
public class ErrorCodeApiImpl implements ErrorCodeApi {

    @Resource
    private ErrorCodeService errorCodeService;

    @Override
    public void autoGenerateErrorCodes(List<ErrorCodeAutoGenerateReqDTO> autoGenerateDTOs) {
        errorCodeService.autoGenerateErrorCodes(autoGenerateDTOs);
    }

    @Override
    public List<ErrorCodeRespDTO> getErrorCodeList(String applicationName, LocalDateTime minUpdateTime) {
        return errorCodeService.getErrorCodeList(applicationName, minUpdateTime);
    }

}
